#!/usr/bin/python
x = "There are %d types of people" %10
binary = "binary"
do_not = "dont't"
y = "Thouse who know %s and thouse who %s." % (binary, do_not)

print x
print y 

print " i said: %r." % x
print "I also said: '%s'." % y 

hilarious = False
joke_evalutation = "Isn't that joke so funny?! %r"


print joke_evalutation % hilarious


w = "This is the left side of..."
e = "a string with a right side."

print w + e 
