#!/usr/bin/python
print "you enter a dark house with two door which door do you got through one or two"

door = raw_input("> ")

if door == "1":
    print "There's a giant bear here eating a cheese cake what do you do"
    print "1. take the cake"
    print "2. Scren at the bear"

    bear = raw=input("> ")
    if bear == "1":
        print " The bear eat your face good job"
    elif bear == "2":
        print "the bear eats your leg off. good job"
    else:
        print "well, doing %s is probably better bear run away" % bear

elif door == "2":
    print "You stare down into the darkess abyss as it calls to you"
    print "1. Follow its command jump into the hole"
    print "2. Keep staring into it"
    print "3. try to find a way to break its control"
    
    insanity = raw_input("> ")

    if insanity == "1":
        print "your sucked into eternal darkness"
    elif insanity == "2":
        print "hand grabs you and drags you in"
    elif insanity == "3":
        print "You lose now you die"
    else:
        print "you die a slow horrible death"
else:
    print "you die from fear" 
    
