#!/usr/bin/python
def cheese_and_crackers(cheese_count, boxes_of_crackers):
    print "you have %d cheese" % cheese_count
    print "you have %d boxes of crackers" % boxes_of_crackers
    print "Man thats enough for a party"
    print "get a blanker. \n"


print "we can just give the function numbers direcly"
cheese_and_crackers(20, 30)

print "or we can have ours"
amount_of_cheese = 10
amount_of_crackers = 50

cheese_and_crackers(amount_of_cheese, amount_of_crackers)

print "we can ever do math inside too"
cheese_and_crackers(10 + 20, 5 + 6)

print "and we can combine the two, Varible and mat" 

cheese_and_crackers(amount_of_cheese + 100, amount_of_crackers + 1000)
